title = "analysis config"
[dates]
start = "01-04-2019"
end = "20-03-2023"
[to_plot.a]
name = "uses_contrast"
type = "percent"#"count"
breakdown = ["Authorising Clinician","has-treatment","has-neoplastic-paraneoplastic","has-ischaemic","Patient Sex","age_at_study","Ordering Clinician"]
